# -*- coding: utf-8 -*-
"""“sentiment-analysis Bot”

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GES2tybU_IhfHxQXdQdq5IVhuUPYgL-W
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install gradio

# Commented out IPython magic to ensure Python compatibility.
# %pip install transformers

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import gradio as gr
# from transformers import pipeline
# 
# sentiment_analyzer = pipeline("sentiment-analysis")
# 
# def analyze_sentiment(text):
#     result = sentiment_analyzer(text)[0]
#     return f"{result['label']} ({result['score']:.2f})"
# 
# iface = gr.Interface(
#     fn=analyze_sentiment,
#     inputs=gr.Textbox(lines=2, placeholder="Enter a sentence here..."),
#     outputs="text",
#     title="Sentiment Analysis Bot",
#     description="Type a sentence and see whether it's positive or negative!"
# )
# 
# iface.launch()
#

!huggingface-cli login

with open("requirements.txt", "w") as f:
    f.write("gradio\ntransformers\ntorch\n")

!gradio deploy

